drop table compte cascade constraints;
drop table customer cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table if exists compte;
drop table if exists customer;
drop table if exists compte;
drop table if exists customer;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
drop table if exists compte;
drop table if exists customer;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKrio5vx6ke6wxxvkbo006gotys;
alter table operation drop foreign key FK5o12n0rda285c7agc6y4apmuy;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
