create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
create table client (id integer not null auto_increment, email varchar(255), nom varchar(255), primary key (id)) engine=InnoDB;
create table commande (id integer not null auto_increment, label varchar(255), client_ayant_passe_la_commande integer, primary key (id)) engine=InnoDB;
alter table commande add constraint FKlqoiqc27cyeel6dalgntjanb4 foreign key (client_ayant_passe_la_commande) references client (id);
