drop table if exists client;
drop table if exists client;
drop table if exists client;
drop table if exists client;
drop table if exists client;
drop table if exists client;
drop table if exists client;
drop table if exists client;
drop table if exists client;
drop table if exists client;
drop table if exists client;
drop table if exists client;
drop table if exists client;
drop table if exists client;
drop table if exists client;
drop table if exists client;
drop table if exists client;
drop table if exists client;
drop table if exists client;
drop table if exists client;
drop table if exists client;
drop table if exists client;
drop table if exists commande;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
alter table commande drop foreign key FKlqoiqc27cyeel6dalgntjanb4;
drop table if exists client;
drop table if exists commande;
