create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe_ingredients (recipe_id bigint not null, ingredients_id bigint not null) engine=InnoDB;
alter table recipe_ingredients add constraint FKg8ssng1dqiwgcptjptldels74 foreign key (ingredients_id) references ingredient (id);
alter table recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe (id);
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe_ingredients (recipe_id bigint not null, ingredients_id bigint not null) engine=InnoDB;
alter table recipe_ingredients add constraint FKg8ssng1dqiwgcptjptldels74 foreign key (ingredients_id) references ingredient (id);
alter table recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe (id);
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe_ingredients (recipe_id bigint not null, ingredients_id bigint not null) engine=InnoDB;
alter table recipe_ingredients add constraint FKg8ssng1dqiwgcptjptldels74 foreign key (ingredients_id) references ingredient (id);
alter table recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe (id);
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe_ingredients (recipe_id bigint not null, ingredients_id bigint not null) engine=InnoDB;
alter table recipe_ingredients add constraint FKg8ssng1dqiwgcptjptldels74 foreign key (ingredients_id) references ingredient (id);
alter table recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe (id);
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe_ingredients (recipe_id bigint not null, ingredients_id bigint not null) engine=InnoDB;
alter table recipe_ingredients add constraint FKg8ssng1dqiwgcptjptldels74 foreign key (ingredients_id) references ingredient (id);
alter table recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe (id);
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe_ingredients (recipe_id bigint not null, ingredients_id bigint not null) engine=InnoDB;
alter table recipe_ingredients add constraint FKg8ssng1dqiwgcptjptldels74 foreign key (ingredients_id) references ingredient (id);
alter table recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe (id);
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe_ingredients (recipe_id bigint not null, ingredients_id bigint not null) engine=InnoDB;
alter table recipe_ingredients add constraint FKg8ssng1dqiwgcptjptldels74 foreign key (ingredients_id) references ingredient (id);
alter table recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe (id);
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe_ingredients (recipe_id bigint not null, ingredients_id bigint not null) engine=InnoDB;
alter table recipe_ingredients add constraint FKg8ssng1dqiwgcptjptldels74 foreign key (ingredients_id) references ingredient (id);
alter table recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe (id);
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe_ingredients (recipe_id bigint not null, ingredients_id bigint not null) engine=InnoDB;
alter table recipe_ingredients add constraint FKg8ssng1dqiwgcptjptldels74 foreign key (ingredients_id) references ingredient (id);
alter table recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe (id);
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe_ingredients (recipe_id bigint not null, ingredients_id bigint not null) engine=InnoDB;
alter table recipe_ingredients add constraint FKg8ssng1dqiwgcptjptldels74 foreign key (ingredients_id) references ingredient (id);
alter table recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe (id);
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe_ingredients (recipe_id bigint not null, ingredients_id bigint not null) engine=InnoDB;
alter table recipe_ingredients add constraint FKg8ssng1dqiwgcptjptldels74 foreign key (ingredients_id) references ingredient (id);
alter table recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe (id);
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe_ingredients (recipe_id bigint not null, ingredients_id bigint not null) engine=InnoDB;
alter table recipe_ingredients add constraint FKg8ssng1dqiwgcptjptldels74 foreign key (ingredients_id) references ingredient (id);
alter table recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe (id);
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe_ingredients (recipe_id bigint not null, ingredients_id bigint not null) engine=InnoDB;
alter table recipe_ingredients add constraint FKg8ssng1dqiwgcptjptldels74 foreign key (ingredients_id) references ingredient (id);
alter table recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe (id);
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe_ingredients (recipe_id bigint not null, ingredients_id bigint not null) engine=InnoDB;
alter table recipe_ingredients add constraint FKg8ssng1dqiwgcptjptldels74 foreign key (ingredients_id) references ingredient (id);
alter table recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe (id);
create table ingredient (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe (id bigint not null auto_increment, label varchar(255), primary key (id)) engine=InnoDB;
create table recipe_ingredients (recipe_id bigint not null, ingredients_id bigint not null) engine=InnoDB;
alter table recipe_ingredients add constraint FKg8ssng1dqiwgcptjptldels74 foreign key (ingredients_id) references ingredient (id);
alter table recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe (id);
