alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
drop table if exists recipe;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
alter table shoplist_recipes drop foreign key FKas3j3gk575ev857d03uy6cnk5;
alter table shoplist_recipes drop foreign key FKotaw9wpgyarga6d3rxuh7iqxv;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists shoplist;
drop table if exists shoplist_recipes;
drop table ingredient cascade constraints;
drop table recipe cascade constraints;
drop table recipe_ingredients cascade constraints;
drop table shoplist cascade constraints;
drop table shoplist_recipes cascade constraints;
drop table ingredient cascade constraints;
drop table recipe cascade constraints;
drop table recipe_ingredients cascade constraints;
drop table shoplist cascade constraints;
drop table shoplist_recipes cascade constraints;
