drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists user_details;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists user_details;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists user_details;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists user_details;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists user_details;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists user_details;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists user_details;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists user_details;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_user_details;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_user_details;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_user_details;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_user_details;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_user_details;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_user_details;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_user_details;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_user_details;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FK91ij3krflf6a76993mxj61qhw;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists aliment;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_products drop foreign key FKhd88gq6u0l4k1xefvv057lg36;
alter table recipe_products drop foreign key FKsiaie72nuy0xhsjhmewt63j1d;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_products;
alter table recipe_products drop foreign key FKhd88gq6u0l4k1xefvv057lg36;
alter table recipe_products drop foreign key FKsiaie72nuy0xhsjhmewt63j1d;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_products;
alter table recipe_products drop foreign key FKhd88gq6u0l4k1xefvv057lg36;
alter table recipe_products drop foreign key FKsiaie72nuy0xhsjhmewt63j1d;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_products;
alter table recipe_products drop foreign key FKhd88gq6u0l4k1xefvv057lg36;
alter table recipe_products drop foreign key FKsiaie72nuy0xhsjhmewt63j1d;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_products;
alter table recipe_products drop foreign key FKhd88gq6u0l4k1xefvv057lg36;
alter table recipe_products drop foreign key FKsiaie72nuy0xhsjhmewt63j1d;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_products;
alter table recipe_products drop foreign key FKhd88gq6u0l4k1xefvv057lg36;
alter table recipe_products drop foreign key FKsiaie72nuy0xhsjhmewt63j1d;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_products;
alter table recipe_products drop foreign key FKhd88gq6u0l4k1xefvv057lg36;
alter table recipe_products drop foreign key FKsiaie72nuy0xhsjhmewt63j1d;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_products;
alter table recipe_products drop foreign key FKhd88gq6u0l4k1xefvv057lg36;
alter table recipe_products drop foreign key FKsiaie72nuy0xhsjhmewt63j1d;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_products;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
drop table if exists product;
drop table if exists recipe;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists user;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists user;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists user;
alter table ingredient drop foreign key FKgg86fhhgm573id99ipfd2br19;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists product;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists user;
