drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
drop table if exists ingredient;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_profile;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists user_details;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists user_details;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists user_details;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists user_details;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists user_details;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists user_details;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists user_details;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
drop table if exists user_details;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_user_details;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_user_details;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_user_details;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_user_details;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_user_details;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_user_details;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_user_details;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists chopy_user_details;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
alter table recipe_ingredients drop foreign key FKg8ssng1dqiwgcptjptldels74;
alter table recipe_ingredients drop foreign key FKhnsmvxdlwxqq6x2wbgnoef5gr;
drop table if exists ingredient;
drop table if exists recipe;
drop table if exists recipe_ingredients;
