drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FK1a5doyjrqncuqgp2decjxcc4k;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client_bisou drop foreign key FKeppxa9y33jao0wgd4ow26cspp;
alter table compte_client_bisou drop foreign key FKb8ftp83drfjyecom9kgudgj7c;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client_bisou;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table client drop foreign key FKin9lm6s50fe989kbfpw7000t9;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table employe drop foreign key FKdbgp2j54tvxls2sa5vlm4ph6u;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
drop table if exists personne;
alter table client drop foreign key FKin9lm6s50fe989kbfpw7000t9;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table employe drop foreign key FKdbgp2j54tvxls2sa5vlm4ph6u;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKd7bi8a3nb8urkipsj0ug5lkdm;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKbhxsypvlnd3a5ahku5beo1ams;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
drop table if exists personne;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
drop table if exists personne;
drop table if exists compte;
drop table if exists operation;
drop table if exists personne_table;
drop table if exists compte;
drop table if exists operation;
drop table if exists personne_table;
drop table if exists compte;
drop table if exists operation;
drop table if exists personne_table;
drop table if exists compte;
drop table if exists operation;
drop table if exists personne_table;
drop table if exists compte;
drop table if exists operation;
drop table if exists personne_table;
drop table if exists personne_table;
drop table if exists personne_table;
drop table if exists personne_table;
drop table if exists compte;
drop table if exists operation;
drop table if exists personne_table;
drop table if exists personne_table;
drop table if exists personne_table;
drop table if exists personne_table;
drop table if exists compte;
drop table if exists operation;
drop table if exists personne_table;
drop table if exists compte;
drop table if exists operation;
drop table if exists personne_table;
drop table if exists personne_table;
drop table if exists personne_table;
drop table if exists personne_table;
drop table if exists personne_table;
drop table if exists personne_table;
